[package]
name = "surt-rs-js"
version = "0.1.3"
edition = "2021"
license = "MIT"
description = "A JS/WASM binding for the surt-rs library"
repository = "https://github.com/mijho/surt-rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.92"
surt-rs = { path = "../../" }
