name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: fmt
      run: make fmt-check
    - name: lint
      run: make lint-check
    - name: Run tests
      run: make test
    - name: Run coverage
      run: |
        cargo install cargo-tarpaulin
        make coverage
